{% set name = "qcachegrind" %}
{% set version = "25.07.90" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://invent.kde.org/sdk/kcachegrind/-/archive/v{{ version }}/kcachegrind-v{{ version }}.tar.gz
  sha256: 3e3f683d92dd990124bd06de7b8be131dec9ae3aea4dbbfe7084fca471ee4da7

build:
  number: 1
  skip: True  # [ppc64le]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - libglx-devel  # [linux]
    - libopengl-devel  # [linux]
    - jom       # [win]
    - m2-patch  # [win]
    - make      # [not win]
    - patch     # [not win]
  host:
    - {{ cdt('libglvnd-glx') }}  # [linux]
    - qt6-main


test:
  commands:
    - test -f ${PREFIX}/bin/cgview       # [unix]
    - test -f ${PREFIX}/bin/qcachegrind  # [unix]
    - if not exist %LIBRARY_BIN%\cgview.exe exit 1       # [win]
    - if not exist %LIBRARY_BIN%\qcachegrind.exe exit 1  # [win]

about:
  home: https://apps.kde.org/en-gb/kcachegrind/
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSES/GPL-2.0-only.txt
  summary: A profiling data visualizer
  description: |
    This tool allows visualisation of profiling data in the callgrind-format.
  doc_url: https://docs.kde.org/stable5/en/kcachegrind/kcachegrind/index.html
  doc_source_url: https://invent.kde.org/sdk/kcachegrind/-/tree/master/doc
  dev_url: https://invent.kde.org/sdk/kcachegrind

extra:
  recipe-maintainers:
    - timkpaine
